# Generated by Django 5.1.7 on 2025-03-18 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extradata',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='extradata',
            name='comments',
        ),
        migrations.AddField(
            model_name='extradata',
            name='activity',
            field=models.CharField(default='Sedentary', max_length=50),
        ),
        migrations.AddField(
            model_name='extradata',
            name='age',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='extradata',
            name='allergies',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='extradata',
            name='avoid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='extradata',
            name='diet',
            field=models.CharField(default='No Restrictions', max_length=50),
        ),
        migrations.AddField(
            model_name='extradata',
            name='gender',
            field=models.CharField(default='Prefer not to say', max_length=20),
        ),
        migrations.AddField(
            model_name='extradata',
            name='goal',
            field=models.CharField(default='Maintain Weight', max_length=50),
        ),
        migrations.AddField(
            model_name='extradata',
            name='height',
            field=models.FloatField(default=170.0, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AddField(
            model_name='extradata',
            name='meals',
            field=models.CharField(default='3', max_length=10),
        ),
        migrations.AddField(
            model_name='extradata',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extradata',
            name='weight',
            field=models.FloatField(default=70.0, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
