# Generated by Django 5.1.7 on 2025-03-19 04:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_extradata_additional_info_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='extradata',
            name='activity',
            field=models.CharField(blank=True, default='Sedentary', max_length=50),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='diet',
            field=models.CharField(blank=True, default='No Restrictions', max_length=50),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='gender',
            field=models.CharField(blank=True, default='Prefer not to say', max_length=20),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='goal',
            field=models.CharField(blank=True, default='Maintain Weight', max_length=50),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='meals',
            field=models.CharField(blank=True, default='3', max_length=10),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userextradata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('food_items', models.TextField(help_text='Comma-separated food items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
