# Generated by Django 5.1.7 on 2025-03-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_nutritiondata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NutritionData',
        ),
    ]
