# Generated by Django 5.1.7 on 2025-03-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_nutritiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymeal',
            name='calintake',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailymeal',
            name='carbintake',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailymeal',
            name='fatintake',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailymeal',
            name='prtointake',
            field=models.FloatField(default=0),
        ),
    ]
