# Generated by Django 5.1.7 on 2025-03-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_dailymeal_calintake_dailymeal_carbintake_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NutritionData',
        ),
        migrations.RemoveField(
            model_name='dailymeal',
            name='calintake',
        ),
        migrations.RemoveField(
            model_name='dailymeal',
            name='carbintake',
        ),
        migrations.RemoveField(
            model_name='dailymeal',
            name='fatintake',
        ),
        migrations.RemoveField(
            model_name='dailymeal',
            name='prtointake',
        ),
    ]
